language: c

sudo: false
cache:
  directories:
  - $HOME/.stack/

matrix:
  include:
  - env: CABALVER=1.22 GHCVER=7.8.4
    secure: awCqPgzrmFol6PTJBpKHibSmgJ9PDD3lDgRoBwQSqYaihrXG/JvzOHt4b77uJIAr8wT7UyYkJxFGb4M7KwURJN3QCSJ5KbB8Rj2blKN9Tb7o0VgdThNT3apzmycy/wniitnHuxupMvyeWmDKJtwP2V/DuGTYF8KKzSluVejRr3A=
    addons: {apt: {packages: [cabal-install-1.22,ghc-7.8.4], sources: [hvr-ghc]}}
  - env: CABALVER=1.22 GHCVER=7.10.2
    secure: awCqPgzrmFol6PTJBpKHibSmgJ9PDD3lDgRoBwQSqYaihrXG/JvzOHt4b77uJIAr8wT7UyYkJxFGb4M7KwURJN3QCSJ5KbB8Rj2blKN9Tb7o0VgdThNT3apzmycy/wniitnHuxupMvyeWmDKJtwP2V/DuGTYF8KKzSluVejRr3A=
    addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3],sources: [hvr-ghc]}}

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar -xzO --wildcards '*/stack' > ~/.local/bin/stack
  - chmod a+x ~/.local/bin/stack
  - openssl aes-256-cbc -K $encrypted_035c7f85af6d_key -iv $encrypted_035c7f85af6d_iv -in .coveralls.yml.enc -out .coveralls.yml -d

install:
  - stack -j 2 setup --no-terminal
  - stack install stack-hpc-coveralls

script:
  - stack -j 2 test --no-terminal --only-snapshot --coverage
  - stack exec shc --repo-token=$REPO_TOKEN distributed-process-extras TimerTests
  - stack exec shc --repo-token=$REPO_TOKEN distributed-process-extras PrimitivesTests
  - stack exec shc --repo-token=$REPO_TOKEN distributed-process-extras LoggerTests

notifications:
  slack:
    secure: g0NP1tkOe3+kI6O0Q1mgT/jPaLjxQ31J26MWouicu2F1Y3p73qTvv/QsOkafRMZDn07HlzgviCP25r7Ytg32pUAFvOh4U4MT2MpO0jUVVGPi4ZiwB+W5AH+HlDtJSickeSZ0AjXZSaGv8nQNegWkeaLQgLBIzrTHU8s0Y9K+whQ=

